/* Runtime seed — DLP rules + gateway config.
   ───────────────────────────────────────────
   Six DLP rules cover the categories the inspector engine detects. Each
   rule is bound to a GRC control (Shadow-AI domain controls added in
   grc/_data.js) so the policy fan-out feels real. */

const NOW = Date.now();
const d = (n) => n * 24 * 60 * 60_000;

export function buildDlpRulesSeed() {
  return [
    {
      id: 'dlp_001',
      name: 'Block credentials to public LLMs',
      description: 'API keys, AWS credentials, private keys, JWTs must never leave the perimeter.',
      enabled: true,
      severity: 'critical',
      match: ['credentials'],
      action: 'block',
      min_confidence: 0.6,
      scope_destinations: ['public-llm'],
      scope_assets: 'all',
      policy_refs: ['SHADOW-AI-001'],
      controls_ref: 'av.dlp.credentials',
      hits_7d: 14,
      created_at: NOW - d(60),
      created_by: 'security@latentbridge.com',
    },
    {
      id: 'dlp_002',
      name: 'Redact customer PII before public LLM',
      description: 'Email, phone, SSN, credit card masked before the prompt is forwarded.',
      enabled: true,
      severity: 'high',
      match: ['customer-pii', 'financial'],
      action: 'redact',
      min_confidence: 0.7,
      scope_destinations: ['public-llm', 'enterprise-saas'],
      scope_assets: 'all',
      policy_refs: ['SHADOW-AI-002', 'GDPR-Art32'],
      controls_ref: 'av.dlp.pii',
      hits_7d: 42,
      created_at: NOW - d(60),
      created_by: 'security@latentbridge.com',
    },
    {
      id: 'dlp_003',
      name: 'Block source code to non-approved AI',
      description: 'Source code blocks routed to non-approved assets are blocked at gateway.',
      enabled: true,
      severity: 'high',
      match: ['source-code'],
      action: 'block',
      min_confidence: 0.55,
      scope_destinations: ['public-llm'],
      scope_assets: ['unapproved', 'quarantined'],
      policy_refs: ['SHADOW-AI-003'],
      controls_ref: 'av.dlp.code',
      hits_7d: 18,
      created_at: NOW - d(45),
      created_by: 'platform-eng@latentbridge.com',
    },
    {
      id: 'dlp_004',
      name: 'Warn on contract / legal content',
      description: 'Contracts and NDAs trigger a banner; user must confirm before sending.',
      enabled: true,
      severity: 'medium',
      match: ['contracts', 'legal'],
      action: 'warn',
      min_confidence: 0.6,
      scope_destinations: ['public-llm'],
      scope_assets: 'all',
      policy_refs: ['SHADOW-AI-004'],
      controls_ref: 'av.dlp.legal',
      hits_7d: 8,
      created_at: NOW - d(40),
      created_by: 'legal@latentbridge.com',
    },
    {
      id: 'dlp_005',
      name: 'Detect prompt-injection attempts',
      description: 'Known bypass phrases are flagged for security review.',
      enabled: true,
      severity: 'high',
      match: ['prompt-injection'],
      action: 'warn',
      min_confidence: 0.8,
      scope_destinations: ['public-llm', 'enterprise-saas', 'internal-agent'],
      scope_assets: 'all',
      policy_refs: ['SHADOW-AI-005', 'OWASP-LLM01'],
      controls_ref: 'av.dlp.prompt-injection',
      hits_7d: 3,
      created_at: NOW - d(30),
      created_by: 'security@latentbridge.com',
    },
    {
      id: 'dlp_006',
      name: 'Redact PHI (HIPAA)',
      description: 'Patient records, diagnosis codes, ICD-10 mentions are masked.',
      enabled: true,
      severity: 'critical',
      match: ['health-phi'],
      action: 'block',
      min_confidence: 0.6,
      scope_destinations: ['public-llm', 'enterprise-saas'],
      scope_assets: 'all',
      policy_refs: ['SHADOW-AI-006', 'HIPAA-164.514'],
      controls_ref: 'av.dlp.phi',
      hits_7d: 0,
      created_at: NOW - d(30),
      created_by: 'compliance@latentbridge.com',
    },
    {
      id: 'dlp_007',
      name: 'Log strategy-class business content',
      description: 'Board decks, roadmap commits, GTM plans logged for audit (no block).',
      enabled: true,
      severity: 'low',
      match: ['business-strategy'],
      action: 'log',
      min_confidence: 0.6,
      scope_destinations: ['public-llm'],
      scope_assets: 'all',
      policy_refs: ['SHADOW-AI-007'],
      controls_ref: 'av.dlp.strategy',
      hits_7d: 24,
      created_at: NOW - d(20),
      created_by: 'security@latentbridge.com',
    },
  ];
}

/* Gateway config — one record describing how the AI gateway is wired in
   the buyer's network. The page edits this and shows a deploy snippet
   per target. */
export function buildGatewayConfigSeed() {
  return {
    id: 'gw_default',
    name: 'AgentVault AI Gateway · default',
    mode: 'inline',
    deployment_target: 'cloudflare-worker',
    routing_rules: [
      { id: 'rt-public-llm',  match: { destination: 'public-llm' },      action: 'inspect-and-enforce' },
      { id: 'rt-enterprise',  match: { destination: 'enterprise-saas' }, action: 'inspect-and-log' },
      { id: 'rt-internal',    match: { destination: 'internal-agent' },  action: 'log-only' },
    ],
    fail_open: false,
    inspect_response: true,
    block_banner: 'Your prompt was blocked by an organizational AI policy. Contact #ai-governance for help.',
    egress_targets: [
      'chat.openai.com',
      'api.openai.com',
      'claude.ai',
      'api.anthropic.com',
      'gemini.google.com',
      'copilot.microsoft.com',
      'perplexity.ai',
      'grammarly.com',
      'notion.so',
      'replit.com',
    ],
    last_compiled_at: NOW - d(2),
    last_deployed_at: NOW - d(2),
    bundle_size_kb: 142,
    rules_active: 7,
  };
}
