/* Seed data for the Govern (control plane) suite — assets, discovery
   events, connectors. Numbers are deterministic so the demo lands the
   same on every reload until the user mutates state. */

const NOW = Date.now();
const m = (n) => n * 60_000;
const h = (n) => n * 60 * 60_000;
const d = (n) => n * 24 * 60 * 60_000;

/* AI Inventory — the unifying primitive. Each row is a discrete AI
   asset the platform knows about. Mix of internal AgentVault agents,
   approved enterprise tools, unmanaged Shadow AI, and items mid-triage. */
export function buildAssetsSeed() {
  return [
    /* ───── Internal AgentVault agents (already governed) ───── */
    {
      id: 'asset_agt_invoice',
      name: 'Invoice triage',
      type: 'internal-agent',
      vendor: 'AgentVault',
      model_family: 'claude-3-5-sonnet',
      owner: 'finance-ops@latentbridge.com',
      department: 'Finance',
      risk_class: 'high',
      approval_state: 'approved',
      discovered_via: 'agent-registry',
      first_seen_at: NOW - d(60),
      last_seen_at:  NOW - m(2),
      user_count_7d: 12,
      traffic_events_7d: 4_812,
      data_categories: ['financial', 'contracts'],
      destination_class: 'internal-agent',
      policy_refs: ['POL-104', 'CTRL-FIN-002'],
      runs_7d: 412,
      cost_7d_usd: 38.40,
    },
    {
      id: 'asset_agt_kyc',
      name: 'KYC verification',
      type: 'internal-agent',
      vendor: 'AgentVault',
      model_family: 'claude-3-5-sonnet',
      owner: 'compliance@latentbridge.com',
      department: 'Compliance',
      risk_class: 'restricted',
      approval_state: 'approved',
      discovered_via: 'agent-registry',
      first_seen_at: NOW - d(45),
      last_seen_at:  NOW - m(8),
      user_count_7d: 8,
      traffic_events_7d: 1_240,
      data_categories: ['customer-pii', 'legal'],
      destination_class: 'internal-agent',
      policy_refs: ['POL-201', 'EU-AI-ACT-Art16'],
      runs_7d: 184,
      cost_7d_usd: 22.10,
    },

    /* ───── Approved enterprise AI ───── */
    {
      id: 'asset_copilot',
      name: 'GitHub Copilot Business',
      type: 'copilot-seat',
      vendor: 'GitHub / Microsoft',
      model_family: 'gpt-4o-codex',
      owner: 'platform-eng@latentbridge.com',
      department: 'Engineering',
      risk_class: 'standard',
      approval_state: 'approved',
      discovered_via: 'github',
      first_seen_at: NOW - d(380),
      last_seen_at:  NOW - m(1),
      user_count_7d: 142,
      traffic_events_7d: 89_400,
      data_categories: ['source-code'],
      destination_class: 'enterprise-saas',
      policy_refs: ['POL-DEV-01'],
      runs_7d: null,
      cost_7d_usd: 720.0,
      notes: '142 of 180 seats active in the last 7 days.',
    },
    {
      id: 'asset_aoai',
      name: 'Azure OpenAI · gpt-4o',
      type: 'byo-llm',
      vendor: 'Microsoft Azure',
      model_family: 'gpt-4o',
      owner: 'platform-eng@latentbridge.com',
      department: 'Platform',
      risk_class: 'standard',
      approval_state: 'approved',
      discovered_via: 'cloud-audit',
      first_seen_at: NOW - d(280),
      last_seen_at:  NOW - m(0),
      user_count_7d: 38,
      traffic_events_7d: 24_120,
      data_categories: [],
      destination_class: 'enterprise-saas',
      policy_refs: ['POL-MODEL-01'],
      cost_7d_usd: 1_840.0,
      notes: 'Approved deployment — used by Studio-built agents and 3 internal apps.',
    },

    /* ───── Pending review ───── */
    {
      id: 'asset_cursor',
      name: 'Cursor for Business',
      type: 'copilot-seat',
      vendor: 'Cursor',
      model_family: 'claude-3-5-sonnet',
      owner: 'frontend-team@latentbridge.com',
      department: 'Engineering',
      risk_class: 'high',
      approval_state: 'pending',
      discovered_via: 'browser-ext',
      first_seen_at: NOW - d(7),
      last_seen_at:  NOW - m(3),
      user_count_7d: 18,
      traffic_events_7d: 12_400,
      data_categories: ['source-code'],
      destination_class: 'public-llm',
      policy_refs: [],
      cost_7d_usd: 0,
      notes: 'Frontend team self-procured. Procurement review in flight.',
    },
    {
      id: 'asset_perplexity-team',
      name: 'Perplexity for Teams',
      type: 'external-saas',
      vendor: 'Perplexity',
      model_family: 'mixed',
      owner: null,
      department: 'Marketing',
      risk_class: 'standard',
      approval_state: 'pending',
      discovered_via: 'casb',
      first_seen_at: NOW - d(11),
      last_seen_at:  NOW - h(2),
      user_count_7d: 9,
      traffic_events_7d: 1_120,
      data_categories: ['business-strategy'],
      destination_class: 'public-llm',
      policy_refs: [],
      cost_7d_usd: 0,
    },

    /* ───── Shadow AI — quarantined or unapproved ───── */
    {
      id: 'asset_chatgpt-personal',
      name: 'ChatGPT (chat.openai.com)',
      type: 'personal-account',
      vendor: 'OpenAI',
      model_family: 'gpt-4o',
      owner: null,
      department: 'Multiple',
      risk_class: 'restricted',
      approval_state: 'quarantined',
      discovered_via: 'proxy',
      first_seen_at: NOW - d(120),
      last_seen_at:  NOW - m(4),
      user_count_7d: 84,
      traffic_events_7d: 4_120,
      data_categories: ['source-code', 'customer-pii', 'financial', 'contracts'],
      destination_class: 'public-llm',
      policy_refs: ['POL-DLP-01'],
      cost_7d_usd: 0,
      notes: '84 users hitting public ChatGPT this week. 12 prompts redacted by gateway, 2 blocked.',
    },
    {
      id: 'asset_claude-personal',
      name: 'Claude.ai (claude.ai)',
      type: 'personal-account',
      vendor: 'Anthropic',
      model_family: 'claude-3-5-sonnet',
      owner: null,
      department: 'Multiple',
      risk_class: 'high',
      approval_state: 'quarantined',
      discovered_via: 'proxy',
      first_seen_at: NOW - d(78),
      last_seen_at:  NOW - m(11),
      user_count_7d: 41,
      traffic_events_7d: 1_840,
      data_categories: ['contracts', 'business-strategy'],
      destination_class: 'public-llm',
      policy_refs: ['POL-DLP-01'],
      cost_7d_usd: 0,
    },
    {
      id: 'asset_grammarly',
      name: 'Grammarly Business AI',
      type: 'browser-extension',
      vendor: 'Grammarly',
      model_family: 'proprietary',
      owner: null,
      department: 'Multiple',
      risk_class: 'high',
      approval_state: 'unknown',
      discovered_via: 'browser-ext',
      first_seen_at: NOW - d(420),
      last_seen_at:  NOW - m(0),
      user_count_7d: 312,
      traffic_events_7d: 41_200,
      data_categories: ['customer-pii', 'business-strategy'],
      destination_class: 'public-llm',
      policy_refs: [],
      cost_7d_usd: 0,
      notes: 'Extension installed via Chrome Web Store on 312 endpoints. No enterprise contract on file.',
    },
    {
      id: 'asset_notion-ai',
      name: 'Notion AI',
      type: 'saas-feature',
      vendor: 'Notion',
      model_family: 'gpt-4o',
      owner: null,
      department: 'Product',
      risk_class: 'standard',
      approval_state: 'unknown',
      discovered_via: 'casb',
      first_seen_at: NOW - d(180),
      last_seen_at:  NOW - h(1),
      user_count_7d: 92,
      traffic_events_7d: 18_400,
      data_categories: ['business-strategy'],
      destination_class: 'enterprise-saas',
      policy_refs: [],
      cost_7d_usd: 0,
    },
    {
      id: 'asset_jasper-personal',
      name: 'Jasper.ai',
      type: 'external-saas',
      vendor: 'Jasper',
      model_family: 'mixed',
      owner: null,
      department: 'Marketing',
      risk_class: 'standard',
      approval_state: 'blocked',
      discovered_via: 'proxy',
      first_seen_at: NOW - d(65),
      last_seen_at:  NOW - d(3),
      user_count_7d: 0,
      traffic_events_7d: 0,
      data_categories: ['business-strategy'],
      destination_class: 'public-llm',
      policy_refs: ['POL-DLP-02'],
      cost_7d_usd: 0,
      notes: 'Blocked at gateway. Marketing team migrated to approved Perplexity deployment.',
    },
    {
      id: 'asset_replit-ghostwriter',
      name: 'Replit Ghostwriter',
      type: 'external-saas',
      vendor: 'Replit',
      model_family: 'mixed',
      owner: null,
      department: 'Engineering',
      risk_class: 'high',
      approval_state: 'unknown',
      discovered_via: 'proxy',
      first_seen_at: NOW - d(42),
      last_seen_at:  NOW - h(6),
      user_count_7d: 4,
      traffic_events_7d: 240,
      data_categories: ['source-code'],
      destination_class: 'public-llm',
      policy_refs: [],
      cost_7d_usd: 0,
    },
    {
      id: 'asset_zoom-ai',
      name: 'Zoom AI Companion',
      type: 'saas-feature',
      vendor: 'Zoom',
      model_family: 'proprietary',
      owner: null,
      department: 'Multiple',
      risk_class: 'high',
      approval_state: 'pending',
      discovered_via: 'saas',
      first_seen_at: NOW - d(95),
      last_seen_at:  NOW - m(40),
      user_count_7d: 412,
      traffic_events_7d: 18_200,
      data_categories: ['business-strategy', 'employee-data'],
      destination_class: 'enterprise-saas',
      policy_refs: [],
      cost_7d_usd: 0,
      notes: 'Recording summaries auto-enabled in tenant. IT review pending.',
    },
    {
      id: 'asset_otter',
      name: 'Otter.ai',
      type: 'external-saas',
      vendor: 'Otter.ai',
      model_family: 'proprietary',
      owner: null,
      department: 'Sales',
      risk_class: 'restricted',
      approval_state: 'quarantined',
      discovered_via: 'oauth',
      first_seen_at: NOW - d(58),
      last_seen_at:  NOW - h(4),
      user_count_7d: 18,
      traffic_events_7d: 320,
      data_categories: ['customer-pii', 'business-strategy'],
      destination_class: 'public-llm',
      policy_refs: ['POL-DLP-01'],
      cost_7d_usd: 0,
      notes: 'Auto-joins meetings — flagged for transcription of customer calls without consent.',
    },
  ];
}

/* Discovery events — the streaming feed. We seed a recent slice so the
   demo has a populated tail. Real systems would tail this from Kafka. */
export function buildEventsSeed() {
  const out = [];
  const samples = [
    { source: 'browser-ext', user: 'alice@latentbridge.com',  asset_id: 'asset_chatgpt-personal',
      destination: 'chat.openai.com', size_kb: 4.2, categories: ['source-code'],          decision: 'redact',
      preview: 'Pasted snippet from billing.py with API key…' },
    { source: 'browser-ext', user: 'mike@latentbridge.com',   asset_id: 'asset_chatgpt-personal',
      destination: 'chat.openai.com', size_kb: 18.4, categories: ['contracts'],            decision: 'block',
      preview: 'Uploaded NDA-acme-2026-Q2.docx · contains counterparty PII' },
    { source: 'proxy',       user: 'sara@latentbridge.com',   asset_id: 'asset_claude-personal',
      destination: 'claude.ai',      size_kb: 1.2, categories: ['business-strategy'],     decision: 'allow',
      preview: 'Plain-text strategy memo · within DLP policy' },
    { source: 'github',      user: 'mike@latentbridge.com',   asset_id: 'asset_copilot',
      destination: 'api.github.com/copilot', size_kb: 0.8, categories: ['source-code'],   decision: 'allow',
      preview: 'Copilot completion · approved seat · public repo' },
    { source: 'casb',        user: 'rohan@latentbridge.com',  asset_id: 'asset_grammarly',
      destination: 'grammarly.com',  size_kb: 2.4, categories: ['customer-pii'],          decision: 'warn',
      preview: 'Customer support reply · 1 email + 1 phone redacted' },
    { source: 'browser-ext', user: 'priya@latentbridge.com',  asset_id: 'asset_chatgpt-personal',
      destination: 'chat.openai.com', size_kb: 0.4, categories: [],                        decision: 'allow',
      preview: 'Generic technical Q&A · no sensitive content detected' },
    { source: 'oauth',       user: 'finance-ops@latentbridge.com', asset_id: 'asset_otter',
      destination: 'otter.ai',       size_kb: 0,   categories: [],                        decision: 'block',
      preview: 'New OAuth grant attempt · quarantined asset' },
    { source: 'proxy',       user: 'alex@latentbridge.com',   asset_id: 'asset_perplexity-team',
      destination: 'perplexity.ai',  size_kb: 1.8, categories: ['business-strategy'],     decision: 'allow',
      preview: 'Market research query · approved-pending asset · monitored' },
    { source: 'cloud-audit', user: 'app:invoice-triage',      asset_id: 'asset_aoai',
      destination: 'azure-openai',   size_kb: 12.4, categories: ['financial'],            decision: 'allow',
      preview: 'Azure OpenAI call · agt_invoiceq · run_9499' },
    { source: 'browser-ext', user: 'jasmin@latentbridge.com', asset_id: 'asset_chatgpt-personal',
      destination: 'chat.openai.com', size_kb: 32.0, categories: ['customer-pii', 'financial'], decision: 'block',
      preview: 'Pasted customer ledger · blocked + ticket SEC-9412 opened' },
    { source: 'crowdstrike', user: 'dan@latentbridge.com',    asset_id: 'asset_replit-ghostwriter',
      destination: 'replit.com',     size_kb: 0,   categories: [],                        decision: 'detect',
      preview: 'New process: replit-desktop.exe · unmanaged AI tool' },
    { source: 'proxy',       user: 'sam@latentbridge.com',    asset_id: 'asset_claude-personal',
      destination: 'claude.ai',      size_kb: 6.2, categories: ['contracts'],             decision: 'redact',
      preview: 'Contract review prompt · 3 PII fields auto-redacted' },
    { source: 'github',      user: 'lila@latentbridge.com',   asset_id: 'asset_copilot',
      destination: 'api.github.com/copilot', size_kb: 1.2, categories: ['source-code'],   decision: 'allow',
      preview: 'Copilot suggestion accepted · auth.ts' },
    { source: 'casb',        user: 'ben@latentbridge.com',    asset_id: 'asset_notion-ai',
      destination: 'notion.so',      size_kb: 8.0, categories: ['business-strategy'],     decision: 'allow',
      preview: 'Notion AI summary on engineering roadmap' },
  ];
  for (let i = 0; i < samples.length; i++) {
    const s = samples[i];
    out.push({
      id: `evt_seed_${(i + 1).toString().padStart(3, '0')}`,
      ts: NOW - m(2 + i * 3),
      ...s,
    });
  }
  return out.sort((a, b) => b.ts - a.ts);
}

/* Connectors enabled in this workspace. We seed three "connected" ones
   so the discovery feed feels populated; the rest live in the catalog
   waiting to be added. */
export function buildConnectorsSeed() {
  return [
    {
      id: 'conn_zscaler',
      kind: 'zscaler',
      name: 'Zscaler · ZIA prod',
      status: 'connected',
      last_event_at: NOW - m(0),
      events_24h: 142_000,
      health: 'green',
      auth_summary: 'tenant: acme.zscalerzero.net',
      created_at: NOW - d(60),
    },
    {
      id: 'conn_browser-ext',
      kind: 'browser-ext',
      name: 'AgentVault Browser ext',
      status: 'connected',
      last_event_at: NOW - m(1),
      events_24h: 18_400,
      health: 'green',
      auth_summary: 'distribution: Chrome MDM + Edge MDM',
      created_at: NOW - d(45),
    },
    {
      id: 'conn_github-copilot',
      kind: 'github-copilot',
      name: 'GitHub Copilot · acme-corp',
      status: 'connected',
      last_event_at: NOW - m(0),
      events_24h: 89_400,
      health: 'green',
      auth_summary: 'org: acme-corp',
      created_at: NOW - d(380),
    },
    {
      id: 'conn_netskope',
      kind: 'netskope',
      name: 'Netskope · acme.goskope.com',
      status: 'connected',
      last_event_at: NOW - m(8),
      events_24h: 64_200,
      health: 'yellow',
      health_detail: 'API rate-limited last hour — 4 batches dropped',
      auth_summary: 'tenant: acme.goskope.com',
      created_at: NOW - d(28),
    },
    {
      id: 'conn_okta',
      kind: 'okta',
      name: 'Okta · system log',
      status: 'connected',
      last_event_at: NOW - m(2),
      events_24h: 8_120,
      health: 'green',
      auth_summary: 'org: acme.okta.com',
      created_at: NOW - d(180),
    },
  ];
}
