/* Seed approval tasks. Twelve realistic rows that span all four trigger
   kinds, every status, and the priority spectrum. Times are anchored to
   `now` at module load so the relative deadlines stay sensible while you
   poke at the demo. */

const NOW = Date.now();
const m = (n) => n * 60_000;
const h = (n) => n * 60 * 60_000;

export function buildSeed() {
  const NOW = Date.now();
  return [
    /* ─── before_run · pre-flight gates ─────────────────────────────── */
    {
      id: 'apt_001',
      run_id: 'run_9499',
      agent_id: 'agt_invoiceq',
      agent_name: 'Invoice triage',
      trigger: 'before_run',
      status: 'pending',
      priority: 'high',
      preview: 'Approve invoice batch run for vendor Acme Corp · $48,210 across 12 invoices',
      context: { vendor: 'Acme Corp', invoice_count: 12, total_usd: 48210, batch_id: 'BATCH-2026-0419' },
      result: null,
      fields_editable: [],
      decisions: ['approve', 'reject'],
      approvers: 'team:finance-ops',
      channel: 'queue:default',
      created_at: NOW - m(14),
      deadline_at: NOW + h(3) + m(46),
      on_timeout: 'reject',
      claimed_by: null,
      claimed_at: null,
      decided_by: null,
      decided_at: null,
      decision: null,
      decided_notes: null,
      edited_fields: null,
      policy_refs: ['POL-104', 'CTRL-FIN-002'],
      cost_usd_so_far: 0,
      tokens: 0,
      trace_step_id: 'sp_root',
      required_expr: 'context.total_usd > 25000',
    },
    {
      id: 'apt_002',
      run_id: 'run_9498',
      agent_id: 'agt_kycverify',
      agent_name: 'KYC verification',
      trigger: 'before_run',
      status: 'pending',
      priority: 'critical',
      preview: 'High-risk customer onboarding: Stellar Holdings Ltd (Cayman) — sanctions screen pending',
      context: { customer: 'Stellar Holdings Ltd', jurisdiction: 'KY', risk_score: 0.84, screening: 'pending' },
      result: null,
      fields_editable: [],
      decisions: ['approve', 'reject'],
      approvers: 'team:compliance',
      channel: 'slack:#kyc-approvals',
      created_at: NOW - m(38),
      deadline_at: NOW + m(22),
      on_timeout: 'escalate',
      claimed_by: null,
      claimed_at: null,
      decided_by: null,
      decided_at: null,
      decision: null,
      decided_notes: null,
      edited_fields: null,
      policy_refs: ['POL-201', 'EU-AI-ACT-Art16', 'CTRL-KYC-EDD'],
      cost_usd_so_far: 0.0042,
      tokens: 1820,
      trace_step_id: 'sp_root',
      required_expr: 'context.risk_score > 0.7',
    },

    /* ─── before_tool · tool guardrails ─────────────────────────────── */
    {
      id: 'apt_003',
      run_id: 'run_9495',
      agent_id: 'agt_invoiceq',
      agent_name: 'Invoice triage',
      trigger: 'before_tool:netsuite.bill',
      status: 'pending',
      priority: 'high',
      preview: 'Confirm before posting bill to NetSuite — Acme Corp $14,200 · GL 6010 · PO mismatch flagged',
      context: { vendor: 'Acme Corp', amount: 14200, gl: '6010', po: 'PO-7821' },
      result: null,
      tool: 'netsuite.bill',
      tool_args: { vendor: 'Acme Corp', amount: 14200, gl_account: '6010', memo: 'Q4 hardware refresh' },
      fields_editable: ['amount', 'gl_account', 'memo'],
      decisions: ['approve', 'reject'],
      approvers: 'finance-managers',
      channel: 'slack:#approvals',
      created_at: NOW - m(8),
      deadline_at: NOW + h(3) + m(52),
      on_timeout: 'reject',
      claimed_by: null,
      claimed_at: null,
      decided_by: null,
      decided_at: null,
      decision: null,
      decided_notes: null,
      edited_fields: null,
      policy_refs: ['CTRL-FIN-002', 'SOX-302'],
      cost_usd_so_far: 0.0061,
      tokens: 4280,
      trace_step_id: 'sp_tool_4',
      required_expr: 'tool_args.amount > 5000',
    },
    {
      id: 'apt_004',
      run_id: 'run_9492',
      agent_id: 'agt_data_analyst',
      agent_name: 'Data Analyst',
      trigger: 'before_tool:slack.post',
      status: 'claimed',
      priority: 'normal',
      preview: 'Confirm before posting #engineering · "Q4 retention dropped 4.2pp — root cause: signup-flow regression…"',
      context: { channel: '#engineering', preview_first_line: 'Q4 retention dropped 4.2pp' },
      result: null,
      tool: 'slack.post',
      tool_args: { channel: '#engineering', text: 'Q4 retention dropped 4.2pp — root cause: signup-flow regression on Android, isolated to versions 4.18+. Recommend rollback.' },
      fields_editable: ['text'],
      decisions: ['approve', 'reject'],
      approvers: 'team:data-platform',
      channel: 'queue:default',
      created_at: NOW - m(22),
      deadline_at: NOW + h(23) + m(38),
      on_timeout: 'reject',
      claimed_by: 'alice@latentbridge.com',
      claimed_at: NOW - m(4),
      decided_by: null,
      decided_at: null,
      decision: null,
      decided_notes: null,
      edited_fields: null,
      policy_refs: ['POL-310'],
      cost_usd_so_far: 0.0103,
      tokens: 7340,
      trace_step_id: 'sp_tool_2',
      required_expr: '',
    },
    {
      id: 'apt_005',
      run_id: 'run_9491',
      agent_id: 'agt_redliner',
      agent_name: 'Contract redliner',
      trigger: 'before_tool:docusign.send',
      status: 'pending',
      priority: 'high',
      preview: 'Send NDA to counterparty (BrightLeaf Ventures) — 4 redlines applied, 1 unresolved comment',
      context: { counterparty: 'BrightLeaf Ventures', redlines: 4, unresolved_comments: 1 },
      result: null,
      tool: 'docusign.send',
      tool_args: { template: 'mutual-nda-v3', recipients: ['legal@brightleaf.vc'], expires_days: 14 },
      fields_editable: ['expires_days'],
      decisions: ['approve', 'reject'],
      approvers: 'legal-team',
      channel: 'email:legal@latentbridge.com',
      created_at: NOW - h(1) - m(12),
      deadline_at: NOW + h(6) + m(48),
      on_timeout: 'reject',
      claimed_by: null,
      claimed_at: null,
      decided_by: null,
      decided_at: null,
      decision: null,
      decided_notes: null,
      edited_fields: null,
      policy_refs: ['POL-LEGAL-04', 'CTRL-LGL-001'],
      cost_usd_so_far: 0.0188,
      tokens: 12420,
      trace_step_id: 'sp_tool_7',
      required_expr: 'context.unresolved_comments > 0',
    },

    /* ─── after_run · post-flight reviews ───────────────────────────── */
    {
      id: 'apt_006',
      run_id: 'run_9489',
      agent_id: 'agt_data_analyst',
      agent_name: 'Data Analyst',
      trigger: 'after_run',
      status: 'pending',
      priority: 'normal',
      preview: 'Review proposed weekly KPI digest before send to leadership · 7 charts, 3 callouts',
      context: { week_of: '2026-05-05', recipients: 8 },
      result: {
        summary: 'Bookings +12% WoW, NRR steady at 118%, churn anomaly in EMEA SMB segment driving cohort drift.',
        charts: 7,
        callouts: ['EMEA SMB churn ↑ 1.4pp', 'Pipeline coverage 3.1x', 'CAC payback 14 mo'],
      },
      fields_editable: ['summary'],
      decisions: ['approve', 'reject'],
      approvers: 'team:operators',
      channel: 'queue:default',
      created_at: NOW - m(48),
      deadline_at: NOW + h(23) + m(12),
      on_timeout: 'approve',
      claimed_by: null,
      claimed_at: null,
      decided_by: null,
      decided_at: null,
      decision: null,
      decided_notes: null,
      edited_fields: null,
      policy_refs: ['POL-COMM-01'],
      cost_usd_so_far: 0.0234,
      tokens: 18620,
      trace_step_id: 'sp_root',
      required_expr: '',
    },
    {
      id: 'apt_007',
      run_id: 'run_9486',
      agent_id: 'agt_redliner',
      agent_name: 'Contract redliner',
      trigger: 'after_run',
      status: 'pending',
      priority: 'low',
      preview: 'Review redline summary before delivery — MSA with Vertex Logistics',
      context: { counterparty: 'Vertex Logistics', doc: 'MSA-vertex-2026-Q2.docx' },
      result: { redlines_total: 23, severity: { critical: 0, major: 4, minor: 19 } },
      fields_editable: [],
      decisions: ['approve', 'reject'],
      approvers: 'legal-team',
      channel: 'queue:default',
      created_at: NOW - h(2) - m(6),
      deadline_at: NOW + h(21) + m(54),
      on_timeout: 'approve',
      claimed_by: null,
      claimed_at: null,
      decided_by: null,
      decided_at: null,
      decision: null,
      decided_notes: null,
      edited_fields: null,
      policy_refs: ['POL-LEGAL-03'],
      cost_usd_so_far: 0.0142,
      tokens: 9840,
      trace_step_id: 'sp_root',
      required_expr: '',
    },

    /* ─── on_demand · clarifying questions ──────────────────────────── */
    {
      id: 'apt_008',
      run_id: 'run_9484',
      agent_id: 'agt_kycverify',
      agent_name: 'KYC verification',
      trigger: 'on_demand',
      status: 'pending',
      priority: 'high',
      preview: 'Beneficial owner record shows two passport numbers issued 6 months apart in different countries — proceed which one?',
      context: { customer: 'NorthStar Capital LLC', conflict_field: 'passport_number', candidates: ['AB1234567 (US, 2025-09)', 'X9876543 (CA, 2026-03)'] },
      result: null,
      fields_editable: ['answer'],
      decisions: ['answered'],
      approvers: 'team:compliance',
      channel: 'slack:#agent-help',
      created_at: NOW - m(11),
      deadline_at: NOW + m(49),
      on_timeout: 'reject',
      claimed_by: null,
      claimed_at: null,
      decided_by: null,
      decided_at: null,
      decision: null,
      decided_notes: null,
      edited_fields: null,
      policy_refs: ['POL-201'],
      cost_usd_so_far: 0.0028,
      tokens: 1240,
      trace_step_id: 'sp_clarify_1',
      required_expr: '',
    },

    /* ─── decided / expired / escalated terminal states ─────────────── */
    {
      id: 'apt_009',
      run_id: 'run_9482',
      agent_id: 'agt_invoiceq',
      agent_name: 'Invoice triage',
      trigger: 'before_tool:netsuite.bill',
      status: 'approved',
      priority: 'normal',
      preview: 'Post bill to NetSuite — Globex Industries $3,420 · GL 6020',
      context: { vendor: 'Globex Industries', amount: 3420, gl: '6020' },
      result: null,
      tool: 'netsuite.bill',
      tool_args: { vendor: 'Globex Industries', amount: 3420, gl_account: '6020' },
      fields_editable: ['amount', 'gl_account'],
      decisions: ['approve', 'reject'],
      approvers: 'finance-managers',
      channel: 'queue:default',
      created_at: NOW - h(4),
      deadline_at: NOW + m(0),
      on_timeout: 'reject',
      claimed_by: 'mike@latentbridge.com',
      claimed_at: NOW - h(3) - m(58),
      decided_by: 'mike@latentbridge.com',
      decided_at: NOW - h(3) - m(46),
      decision: 'approve',
      decided_notes: 'Verified PO match — proceed.',
      edited_fields: null,
      policy_refs: ['CTRL-FIN-002'],
      cost_usd_so_far: 0.0058,
      tokens: 4120,
      trace_step_id: 'sp_tool_3',
      required_expr: '',
    },
    {
      id: 'apt_010',
      run_id: 'run_9479',
      agent_id: 'agt_redliner',
      agent_name: 'Contract redliner',
      trigger: 'after_run',
      status: 'rejected',
      priority: 'normal',
      preview: 'Review redline summary — Pinnacle Holdings DPA',
      context: { counterparty: 'Pinnacle Holdings', doc: 'DPA-pinnacle-2026.docx' },
      result: { redlines_total: 41, severity: { critical: 2, major: 8, minor: 31 } },
      fields_editable: [],
      decisions: ['approve', 'reject'],
      approvers: 'legal-team',
      channel: 'email:legal@latentbridge.com',
      created_at: NOW - h(6),
      deadline_at: NOW - h(0),
      on_timeout: 'approve',
      claimed_by: 'sara@latentbridge.com',
      claimed_at: NOW - h(5) - m(40),
      decided_by: 'sara@latentbridge.com',
      decided_at: NOW - h(5) - m(20),
      decision: 'reject',
      decided_notes: '2 critical findings on data-residency clause — agent missed §7.3. Re-run with stricter prompt.',
      edited_fields: null,
      policy_refs: ['POL-LEGAL-03', 'GDPR-Art28'],
      cost_usd_so_far: 0.0212,
      tokens: 14620,
      trace_step_id: 'sp_root',
      required_expr: '',
    },
    {
      id: 'apt_011',
      run_id: 'run_9476',
      agent_id: 'agt_data_analyst',
      agent_name: 'Data Analyst',
      trigger: 'before_tool:hubspot.create_deal',
      status: 'expired',
      priority: 'low',
      preview: 'Create HubSpot deal — Verdant Solutions · $42,000 ARR · 60% close confidence',
      context: { account: 'Verdant Solutions', arr: 42000, confidence: 0.6 },
      result: null,
      tool: 'hubspot.create_deal',
      tool_args: { account: 'Verdant Solutions', arr: 42000, stage: 'discovery' },
      fields_editable: ['arr', 'stage'],
      decisions: ['approve', 'reject'],
      approvers: 'team:revops',
      channel: 'queue:default',
      created_at: NOW - h(28),
      deadline_at: NOW - h(4),
      on_timeout: 'reject',
      claimed_by: null,
      claimed_at: null,
      decided_by: 'system:timeout',
      decided_at: NOW - h(4),
      decision: 'reject',
      decided_notes: 'Auto-rejected — 24h timeout reached.',
      edited_fields: null,
      policy_refs: ['POL-REV-02'],
      cost_usd_so_far: 0.0044,
      tokens: 2980,
      trace_step_id: 'sp_tool_2',
      required_expr: '',
    },
    {
      id: 'apt_012',
      run_id: 'run_9474',
      agent_id: 'agt_kycverify',
      agent_name: 'KYC verification',
      trigger: 'before_run',
      status: 'escalated',
      priority: 'critical',
      preview: 'Sanctions hit on entity "Lazarus Holdings" — escalation required',
      context: { customer: 'Lazarus Holdings', sanctions_list: 'OFAC-SDN', match_score: 0.97 },
      result: null,
      fields_editable: [],
      decisions: ['approve', 'reject'],
      approvers: 'team:compliance',
      channel: 'slack:#kyc-approvals',
      created_at: NOW - h(8),
      deadline_at: NOW - h(7),
      on_timeout: 'escalate',
      claimed_by: null,
      claimed_at: null,
      decided_by: 'system:timeout',
      decided_at: NOW - h(7),
      decision: 'escalate',
      decided_notes: 'Escalated to MLRO@latentbridge.com per OFAC match policy.',
      edited_fields: null,
      policy_refs: ['POL-201', 'OFAC-SDN', 'EU-AI-ACT-Art16'],
      cost_usd_so_far: 0.0072,
      tokens: 3640,
      trace_step_id: 'sp_root',
      required_expr: 'context.match_score > 0.8',
    },
  ];
}

/* Nudge seed — keyed by run_id. Two examples so the run page has visible
   audit history even before a user sends anything. Runs that exist in the
   runs index (run_9501..) and are in `running` status get one of these. */
export function buildNudgesSeed() {
  const NOW = Date.now();
  return {
    run_9499: [
      {
        id: 'nudge_seed_a',
        run_id: 'run_9499',
        sent_by: 'sara@latentbridge.com',
        sent_at: NOW - 12 * 60_000,
        kind: 'guidance',
        body: 'For invoices from Acme this week, prefer GL 6010 even if the agent thinks 6020 — there\'s a coding migration in progress.',
        redirect: null,
        consumed_at: NOW - 11 * 60_000,
        agent_reaction: 'Got it — pinning GL 6010 for Acme invoices this run. Will note in audit.',
      },
    ],
    run_9495: [
      {
        id: 'nudge_seed_b',
        run_id: 'run_9495',
        sent_by: 'mike@latentbridge.com',
        sent_at: NOW - 4 * 60_000,
        kind: 'stop',
        body: 'Stop now. Halt at the next safe checkpoint and wait for human approval.',
        redirect: null,
        consumed_at: null,
        agent_reaction: null,
      },
    ],
  };
}
