/* Vendor presets for the add-server wizard.
   Each preset seeds transport / endpoint / auth kind / scope hints and a
   plausible mocked tool list for discovery. "Custom" lets users type any URL. */

export const VENDORS = [
  {
    id: 'custom',
    label: 'Custom server',
    blurb: 'Any MCP-compatible endpoint. You configure everything.',
    icon: 'plug',
    transport: 'streamable-http',
    endpoint: '',
    authKinds: ['oauth', 'bearer', 'header', 'mtls', 'none'],
    defaultAuth: 'bearer',
    scopes: [],
    mockTools: [],
  },
  {
    id: 'atlassian',
    label: 'Atlassian',
    blurb: 'Jira + Confluence + Bitbucket unified MCP gateway.',
    icon: 'plug',
    transport: 'streamable-http',
    endpoint: 'https://mcp.atlassian.com',
    authKinds: ['oauth'],
    defaultAuth: 'oauth',
    scopes: ['read:jira-work', 'write:jira-work', 'read:confluence-content', 'read:confluence-space'],
    mockTools: [
      { name: 'jira.search',          description: 'Search Jira issues by JQL.',                  riskLevel: 'low'  },
      { name: 'jira.create_issue',    description: 'Create a new Jira issue.',                    riskLevel: 'high' },
      { name: 'jira.add_comment',     description: 'Add a comment to an existing issue.',          riskLevel: 'med'  },
      { name: 'jira.transition',      description: 'Transition an issue to a new status.',         riskLevel: 'high' },
      { name: 'confluence.page.get',  description: 'Fetch a Confluence page by ID.',               riskLevel: 'low'  },
      { name: 'confluence.page.search', description: 'Search Confluence across spaces.',           riskLevel: 'low'  },
    ],
    mockResources: [{ uri: 'jira://issue/{key}', description: 'Jira issue resource by key.' }],
  },
  {
    id: 'github',
    label: 'GitHub',
    blurb: 'Repos, pull requests, issues, and actions.',
    icon: 'plug',
    transport: 'streamable-http',
    endpoint: 'https://api.githubcopilot.com/mcp',
    authKinds: ['oauth', 'bearer'],
    defaultAuth: 'oauth',
    scopes: ['repo', 'issues:read', 'pull_requests:write'],
    mockTools: [
      { name: 'repo.search',       description: 'Search repositories and code.',         riskLevel: 'low'  },
      { name: 'issue.get',         description: 'Fetch an issue by number.',              riskLevel: 'low'  },
      { name: 'issue.comment',     description: 'Post a comment on an issue.',            riskLevel: 'med'  },
      { name: 'pr.review',         description: 'Submit a PR review.',                     riskLevel: 'high' },
      { name: 'workflow.dispatch', description: 'Trigger a GitHub Actions workflow.',       riskLevel: 'high' },
    ],
  },
  {
    id: 'linear',
    label: 'Linear',
    blurb: 'Tickets, projects, cycles.',
    icon: 'plug',
    transport: 'streamable-http',
    endpoint: 'https://mcp.linear.app/sse',
    authKinds: ['oauth'],
    defaultAuth: 'oauth',
    scopes: ['read', 'write'],
    mockTools: [
      { name: 'issue.list',   description: 'List issues in a team.',     riskLevel: 'low'  },
      { name: 'issue.create', description: 'Create an issue.',            riskLevel: 'med'  },
      { name: 'issue.update', description: 'Update an issue status or assignee.', riskLevel: 'med' },
    ],
  },
  {
    id: 'figma',
    label: 'Figma',
    blurb: 'Read files, leave comments, export frames.',
    icon: 'plug',
    transport: 'streamable-http',
    endpoint: 'https://mcp.figma.com',
    authKinds: ['oauth', 'bearer'],
    defaultAuth: 'oauth',
    scopes: ['file_content:read', 'file_comments:write'],
    mockTools: [
      { name: 'file.get',      description: 'Fetch a Figma file by key.',                riskLevel: 'low' },
      { name: 'comment.add',   description: 'Post a comment on a frame.',                riskLevel: 'med' },
      { name: 'frame.export',  description: 'Export a frame as PNG / SVG / PDF.',        riskLevel: 'low' },
    ],
  },
  {
    id: 'stripe',
    label: 'Stripe',
    blurb: 'Payments, subscriptions, customers — read/write.',
    icon: 'plug',
    transport: 'streamable-http',
    endpoint: 'https://mcp.stripe.com/v1',
    authKinds: ['oauth', 'bearer'],
    defaultAuth: 'bearer',
    scopes: ['read_write'],
    mockTools: [
      { name: 'customer.search',  description: 'Search customers by email / ID.',   riskLevel: 'low'  },
      { name: 'charge.refund',    description: 'Issue a refund for a charge.',      riskLevel: 'high' },
      { name: 'subscription.cancel', description: 'Cancel a subscription.',          riskLevel: 'high' },
    ],
  },
  {
    id: 'notion',
    label: 'Notion',
    blurb: 'Databases, pages, comments.',
    icon: 'docs',
    transport: 'streamable-http',
    endpoint: 'https://mcp.notion.com',
    authKinds: ['oauth'],
    defaultAuth: 'oauth',
    scopes: ['read_content', 'update_content', 'read_comments'],
    mockTools: [
      { name: 'page.get',       description: 'Fetch a Notion page by ID.',                   riskLevel: 'low' },
      { name: 'page.update',    description: 'Patch page properties.',                        riskLevel: 'med' },
      { name: 'db.query',       description: 'Query a Notion database.',                      riskLevel: 'low' },
      { name: 'comment.post',   description: 'Add a comment to a page.',                      riskLevel: 'med' },
    ],
  },
  {
    id: 'databases',
    label: 'Databases',
    blurb: 'Universal database MCP — connect Postgres, MySQL, Snowflake, BigQuery, Redshift, Databricks, MSSQL, Oracle, ClickHouse via one server. Schema introspection, query, plan, and gated writes.',
    icon: 'db',
    transport: 'streamable-http',
    endpoint: 'https://mcp.agentvault.io/databases',
    authKinds: ['oauth', 'bearer', 'mtls', 'header'],
    defaultAuth: 'bearer',
    scopes: ['db:read', 'db:write', 'db:ddl', 'db:explain', 'db:admin'],
    /* Tools — grouped by lifecycle stage. The deliberately-broad surface lets
       the agent reason about a database end-to-end while the risk tiers + per-tool
       approval flags scope the blast radius:
         low   → read-only metadata & SELECTs
         med   → DML writes, transactions
         high  → DDL, role/grant/admin operations */
    mockTools: [
      // ─── Connection & catalog ───
      { name: 'db.connections.list',   description: 'List configured database connections in this server.',                        riskLevel: 'low'  },
      { name: 'db.connection.test',    description: 'Test reachability + auth for a connection. Returns version + role + RLS info.', riskLevel: 'low'  },
      // ─── Schema introspection (low risk, high agent value) ───
      { name: 'db.databases.list',     description: 'List databases in a connection.',                                              riskLevel: 'low'  },
      { name: 'db.schemas.list',       description: 'List schemas in a database.',                                                   riskLevel: 'low'  },
      { name: 'db.tables.list',        description: 'List tables/views in a schema, with row-count estimates.',                      riskLevel: 'low'  },
      { name: 'db.table.describe',     description: 'Describe a table: columns + types + nullable + PK/FK + comments + size.',      riskLevel: 'low'  },
      { name: 'db.table.sample',       description: 'Return a small (LIMIT 100) random sample of rows for inspection.',              riskLevel: 'low'  },
      { name: 'db.indexes.list',       description: 'List indexes on a table with usage stats and bloat estimates.',                 riskLevel: 'low'  },
      { name: 'db.foreign_keys.list',  description: 'List foreign-key relationships across a schema (canonical join paths).',        riskLevel: 'low'  },
      // ─── Query & analysis (low → med depending on parameters) ───
      { name: 'db.sql.query',          description: 'Run a parameterized SELECT. Read-only role enforced; results capped at row + byte limits.', riskLevel: 'low'  },
      { name: 'db.sql.explain',        description: 'EXPLAIN [ANALYZE] a query and return the plan as structured JSON.',             riskLevel: 'low'  },
      { name: 'db.stats.summarize',    description: 'Return numeric/percentile/cardinality stats for selected columns.',             riskLevel: 'low'  },
      { name: 'db.lineage.fetch',      description: 'Fetch upstream/downstream lineage for a table from the warehouse catalog.',     riskLevel: 'low'  },
      // ─── Writes (medium — dual-control encouraged) ───
      { name: 'db.sql.dml',            description: 'Execute INSERT / UPDATE / DELETE inside an explicit transaction. Dry-run first.', riskLevel: 'med'  },
      { name: 'db.txn.begin',          description: 'Begin a named transaction. Must be committed or rolled back within TTL.',       riskLevel: 'med'  },
      { name: 'db.txn.commit',         description: 'Commit a named transaction.',                                                    riskLevel: 'med'  },
      { name: 'db.txn.rollback',       description: 'Roll back a named transaction.',                                                 riskLevel: 'low'  },
      { name: 'db.bulk.upsert',        description: 'Bulk upsert rows from a staged file. Generates a diff summary before commit.',  riskLevel: 'med'  },
      // ─── DDL & admin (high — approval-gated by default) ───
      { name: 'db.sql.ddl',            description: 'Execute DDL (CREATE / ALTER / DROP). Always dry-runs first; requires approval.', riskLevel: 'high' },
      { name: 'db.role.grant',         description: 'Grant a role / privilege to a user. Requires approval.',                          riskLevel: 'high' },
      { name: 'db.role.revoke',        description: 'Revoke a role / privilege from a user. Requires approval.',                       riskLevel: 'high' },
      { name: 'db.snapshot.create',    description: 'Create a point-in-time snapshot before a destructive operation.',                 riskLevel: 'med'  },
      { name: 'db.replica.failover',   description: 'Promote a replica. Requires approval; emits incident event.',                     riskLevel: 'high' },
      // ─── Operational ───
      { name: 'db.queries.list_running', description: 'List currently-running queries with elapsed time + caller.',                    riskLevel: 'low'  },
      { name: 'db.queries.cancel',     description: 'Cancel a running query by id. Requires approval.',                                riskLevel: 'high' },
      { name: 'db.locks.list',         description: 'List blocking locks across active sessions.',                                     riskLevel: 'low'  },
    ],
    /* Resources — MCP resources expose URI-addressable read targets the agent
       can attach to a prompt. The runtime resolves these and inlines them as
       ground-truth context. */
    mockResources: [
      { uri: 'db://{connectionId}',                                description: 'A registered database connection.' },
      { uri: 'db://{connectionId}/{database}',                     description: 'A database within a connection.' },
      { uri: 'db://{connectionId}/{database}/{schema}',            description: 'A schema (namespace) within a database.' },
      { uri: 'db://{connectionId}/{database}/{schema}/{table}',    description: 'A table or view — resolves to a typed schema description.' },
      { uri: 'db://{connectionId}/{database}/{schema}/{table}/columns', description: 'Column-level metadata: types, nullability, comments.' },
      { uri: 'db://{connectionId}/{database}/{schema}/{table}/sample',  description: 'A 100-row deterministic sample of the table.' },
      { uri: 'db://lineage/{table}',                               description: 'Upstream + downstream lineage for a table.' },
      { uri: 'db://{connectionId}/queries/{queryId}',              description: 'A previously-run query with its plan + results metadata.' },
    ],
  },
  {
    id: 'slack',
    label: 'Slack',
    blurb: 'Channels, DMs, threads, search, reactions. Uses Slack OAuth (free workspace tier supported). Works for agent notifications + interactive approvals.',
    icon: 'plug',
    transport: 'streamable-http',
    endpoint: 'https://slack.com/mcp',
    authKinds: ['oauth', 'bearer'],
    defaultAuth: 'oauth',
    scopes: ['channels:read', 'chat:write', 'chat:write.public', 'groups:read', 'im:read', 'reactions:write', 'search:read'],
    mockTools: [
      { name: 'slack.channels.list',     description: 'List channels in the workspace.',                          riskLevel: 'low'  },
      { name: 'slack.messages.search',   description: 'Search messages across channels you can see.',             riskLevel: 'low'  },
      { name: 'slack.message.post',      description: 'Post a message to a channel.',                              riskLevel: 'med'  },
      { name: 'slack.message.dm',        description: 'Send a direct message to a user.',                          riskLevel: 'med'  },
      { name: 'slack.thread.reply',      description: 'Reply in a thread.',                                         riskLevel: 'med'  },
      { name: 'slack.reaction.add',      description: 'Add a reaction to a message.',                               riskLevel: 'low'  },
      { name: 'slack.user.lookup',       description: 'Look up a user by id or email.',                             riskLevel: 'low'  },
    ],
    mockResources: [
      { uri: 'slack://channel/{channelId}', description: 'A channel by id (with members + purpose).' },
      { uri: 'slack://message/{ts}',         description: 'A specific message by timestamp.' },
    ],
  },
  {
    id: 'cloudflare',
    label: 'Cloudflare',
    blurb: 'Manage Workers, Pages, KV, R2, D1, DNS, and Zero Trust from your agents. Free dev plan covers most. OAuth or API token auth.',
    icon: 'plug',
    transport: 'streamable-http',
    endpoint: 'https://api.cloudflare.com/mcp',
    authKinds: ['oauth', 'bearer'],
    defaultAuth: 'oauth',
    scopes: ['account:read', 'workers:write', 'kv:write', 'r2:write', 'pages:write', 'dns:read'],
    mockTools: [
      { name: 'cf.workers.deploy',     description: 'Deploy a Worker script.',                                     riskLevel: 'high' },
      { name: 'cf.workers.tail',       description: 'Stream live logs from a Worker.',                              riskLevel: 'low'  },
      { name: 'cf.kv.get',             description: 'Read a key from a KV namespace.',                              riskLevel: 'low'  },
      { name: 'cf.kv.put',             description: 'Write a key into a KV namespace.',                             riskLevel: 'med'  },
      { name: 'cf.r2.list',            description: 'List objects in an R2 bucket.',                                riskLevel: 'low'  },
      { name: 'cf.r2.get',             description: 'Fetch an object from an R2 bucket.',                           riskLevel: 'low'  },
      { name: 'cf.r2.put',             description: 'Upload an object to an R2 bucket.',                            riskLevel: 'med'  },
      { name: 'cf.pages.deployment.create', description: 'Trigger a Cloudflare Pages deployment.',                  riskLevel: 'high' },
      { name: 'cf.dns.records.list',   description: 'List DNS records on a zone.',                                  riskLevel: 'low'  },
      { name: 'cf.dns.records.update', description: 'Update a DNS record. Requires approval.',                      riskLevel: 'high' },
    ],
    mockResources: [
      { uri: 'cf://account/{accountId}',        description: 'A Cloudflare account.' },
      { uri: 'cf://account/{accountId}/zone/{zoneId}', description: 'A DNS zone.' },
    ],
  },
  {
    id: 'hubspot',
    label: 'HubSpot',
    blurb: 'CRM contacts + companies + deals + tickets + email engagement. Free CRM tier supported via OAuth.',
    icon: 'plug',
    transport: 'streamable-http',
    endpoint: 'https://api.hubapi.com/mcp',
    authKinds: ['oauth', 'bearer'],
    defaultAuth: 'oauth',
    scopes: ['crm.objects.contacts.read', 'crm.objects.contacts.write', 'crm.objects.companies.read', 'crm.objects.deals.read', 'crm.objects.deals.write', 'tickets'],
    mockTools: [
      { name: 'hubspot.contacts.search', description: 'Search contacts by email / name / property.',               riskLevel: 'low'  },
      { name: 'hubspot.contact.get',     description: 'Fetch a contact by id.',                                    riskLevel: 'low'  },
      { name: 'hubspot.contact.create',  description: 'Create a contact.',                                          riskLevel: 'med'  },
      { name: 'hubspot.contact.update',  description: 'Update contact properties.',                                 riskLevel: 'med'  },
      { name: 'hubspot.companies.search',description: 'Search companies.',                                          riskLevel: 'low'  },
      { name: 'hubspot.deals.search',    description: 'Search deals by stage / amount / owner.',                    riskLevel: 'low'  },
      { name: 'hubspot.deal.update',     description: 'Update a deal stage / amount. Approval recommended.',        riskLevel: 'high' },
      { name: 'hubspot.tickets.create',  description: 'Create a support ticket.',                                   riskLevel: 'med'  },
    ],
    mockResources: [
      { uri: 'hubspot://contact/{id}', description: 'A contact record.' },
      { uri: 'hubspot://deal/{id}',    description: 'A deal record.' },
    ],
  },
  {
    id: 'asana',
    label: 'Asana',
    blurb: 'Tasks, projects, sections, comments. Free workspace tier supported. OAuth or personal access token.',
    icon: 'plug',
    transport: 'streamable-http',
    endpoint: 'https://app.asana.com/api/mcp',
    authKinds: ['oauth', 'bearer'],
    defaultAuth: 'oauth',
    scopes: ['default'],
    mockTools: [
      { name: 'asana.tasks.search',   description: 'Search tasks by project, assignee, or query.',  riskLevel: 'low' },
      { name: 'asana.task.get',       description: 'Fetch a task by gid.',                            riskLevel: 'low' },
      { name: 'asana.task.create',    description: 'Create a task.',                                  riskLevel: 'med' },
      { name: 'asana.task.update',    description: 'Update a task (status, due date, assignee).',     riskLevel: 'med' },
      { name: 'asana.task.comment',   description: 'Add a comment to a task.',                         riskLevel: 'low' },
      { name: 'asana.projects.list',  description: 'List projects in a workspace.',                    riskLevel: 'low' },
    ],
    mockResources: [
      { uri: 'asana://task/{gid}',    description: 'A task by gid.' },
      { uri: 'asana://project/{gid}', description: 'A project by gid.' },
    ],
  },
  {
    id: 'pagerduty',
    label: 'PagerDuty',
    blurb: 'Incidents, services, schedules. Free tier (Free plan up to 5 users). REST API token-based auth.',
    icon: 'plug',
    transport: 'streamable-http',
    endpoint: 'https://api.pagerduty.com/mcp',
    authKinds: ['bearer', 'oauth'],
    defaultAuth: 'bearer',
    scopes: ['incidents:read', 'incidents:write', 'services:read', 'schedules:read'],
    mockTools: [
      { name: 'pd.incidents.list',     description: 'List open incidents.',                              riskLevel: 'low'  },
      { name: 'pd.incident.get',       description: 'Fetch an incident with timeline.',                   riskLevel: 'low'  },
      { name: 'pd.incident.acknowledge',description: 'Acknowledge an incident.',                          riskLevel: 'med'  },
      { name: 'pd.incident.resolve',   description: 'Resolve an incident.',                                riskLevel: 'high' },
      { name: 'pd.incident.create',    description: 'Trigger a new incident.',                             riskLevel: 'high' },
      { name: 'pd.services.list',      description: 'List configured services.',                           riskLevel: 'low'  },
      { name: 'pd.schedule.oncall',    description: 'Find who is on call right now.',                      riskLevel: 'low'  },
    ],
    mockResources: [
      { uri: 'pd://incident/{id}', description: 'An incident with full timeline.' },
      { uri: 'pd://service/{id}',  description: 'A service definition.' },
    ],
  },
  {
    id: 'datadog',
    label: 'Datadog',
    blurb: 'Metrics, logs, monitors, dashboards, APM. Free trial; permanent free tier on small workloads. API key + Application key auth.',
    icon: 'plug',
    transport: 'streamable-http',
    endpoint: 'https://api.datadoghq.com/mcp',
    authKinds: ['header', 'bearer'],
    defaultAuth: 'header',
    scopes: ['metrics_read', 'logs_read', 'monitors_read', 'monitors_write', 'dashboards_read'],
    mockTools: [
      { name: 'dd.metrics.query',    description: 'Run a metrics query (Datadog query language).',     riskLevel: 'low'  },
      { name: 'dd.logs.search',      description: 'Search logs with a filter expression.',              riskLevel: 'low'  },
      { name: 'dd.monitors.list',    description: 'List monitors with current state.',                  riskLevel: 'low'  },
      { name: 'dd.monitor.get',      description: 'Fetch a monitor with full definition.',              riskLevel: 'low'  },
      { name: 'dd.monitor.mute',     description: 'Mute a monitor for a duration.',                     riskLevel: 'med'  },
      { name: 'dd.dashboard.get',    description: 'Fetch a dashboard definition.',                      riskLevel: 'low'  },
      { name: 'dd.events.list',      description: 'List events in a time window.',                      riskLevel: 'low'  },
      { name: 'dd.synthetics.run',   description: 'Trigger a synthetic test on demand.',                riskLevel: 'med'  },
    ],
    mockResources: [
      { uri: 'dd://monitor/{id}',   description: 'A monitor with full definition + state.' },
      { uri: 'dd://dashboard/{id}', description: 'A dashboard with widgets.' },
    ],
  },
  {
    id: 'brave',
    label: 'Brave Search',
    blurb: 'Independent web index. Free tier: 1 query/second. Bearer-token auth via API key.',
    icon: 'plug',
    transport: 'streamable-http',
    endpoint: 'https://api.search.brave.com/mcp',
    authKinds: ['bearer'],
    defaultAuth: 'bearer',
    scopes: [],
    mockTools: [
      { name: 'brave.web.search',   description: 'Web search with site categorization signals.',  riskLevel: 'low' },
      { name: 'brave.news.search',  description: 'Search news with freshness filters.',           riskLevel: 'low' },
      { name: 'brave.images.search',description: 'Image search.',                                   riskLevel: 'low' },
    ],
    mockResources: [],
  },
  {
    id: 'tavily',
    label: 'Tavily',
    blurb: 'Search built for LLM agents — pre-summarized snippets + structured citations. Free tier: 1,000 calls/month.',
    icon: 'plug',
    transport: 'streamable-http',
    endpoint: 'https://api.tavily.com/mcp',
    authKinds: ['bearer'],
    defaultAuth: 'bearer',
    scopes: [],
    mockTools: [
      { name: 'tavily.search',     description: 'Search with optional Tavily-generated answer.',     riskLevel: 'low' },
      { name: 'tavily.extract',    description: 'Fetch + clean URLs to LLM-friendly markdown.',      riskLevel: 'low' },
      { name: 'tavily.research',   description: 'Multi-step deep research with citation graph.',      riskLevel: 'low' },
    ],
    mockResources: [],
  },
  {
    id: 'exa',
    label: 'Exa',
    blurb: 'Neural search for technical, academic, and long-tail content. Free tier: $10 credit / 1k searches.',
    icon: 'plug',
    transport: 'streamable-http',
    endpoint: 'https://api.exa.ai/mcp',
    authKinds: ['bearer'],
    defaultAuth: 'bearer',
    scopes: [],
    mockTools: [
      { name: 'exa.search',          description: 'Neural / keyword / auto search with full-text option.', riskLevel: 'low' },
      { name: 'exa.find_similar',    description: 'Find pages semantically similar to a URL.',               riskLevel: 'low' },
      { name: 'exa.contents',        description: 'Fetch full text + highlights for retrieved URLs.',        riskLevel: 'low' },
    ],
    mockResources: [],
  },
  {
    id: 'zapier',
    label: 'Zapier MCP',
    blurb: 'Bridge to ~7,000 SaaS actions through a single MCP. Free tier covers low-volume use; paid plans scale up. OAuth-based.',
    icon: 'plug',
    transport: 'streamable-http',
    endpoint: 'https://mcp.zapier.com',
    authKinds: ['oauth', 'bearer'],
    defaultAuth: 'oauth',
    scopes: [],
    mockTools: [
      { name: 'zapier.actions.list',   description: 'List actions exposed for the connected account.',      riskLevel: 'low'  },
      { name: 'zapier.actions.run',    description: 'Run any exposed action by name with a JSON payload.',  riskLevel: 'high' },
      { name: 'zapier.zaps.list',      description: 'List Zaps + their state.',                              riskLevel: 'low'  },
      { name: 'zapier.zap.toggle',     description: 'Enable / disable a Zap.',                                riskLevel: 'med'  },
    ],
    mockResources: [
      { uri: 'zapier://action/{id}', description: 'A configured Zapier action.' },
    ],
  },
  {
    id: 'supabase',
    label: 'Supabase',
    blurb: 'Postgres + Auth + Storage + Realtime. Free tier covers 500MB DB / 1GB storage. Service-role key or user JWT auth.',
    icon: 'db',
    transport: 'streamable-http',
    endpoint: 'https://api.supabase.com/mcp',
    authKinds: ['bearer'],
    defaultAuth: 'bearer',
    scopes: ['db.read', 'db.write', 'auth.users.read', 'storage.read', 'storage.write'],
    mockTools: [
      { name: 'sb.db.query',          description: 'Run a SELECT against a project DB. RLS enforced.',          riskLevel: 'low'  },
      { name: 'sb.db.execute',        description: 'Run an INSERT/UPDATE/DELETE in a transaction.',              riskLevel: 'med'  },
      { name: 'sb.tables.list',       description: 'List tables in a project schema.',                            riskLevel: 'low'  },
      { name: 'sb.auth.users.list',   description: 'List users in the project Auth.',                              riskLevel: 'med'  },
      { name: 'sb.storage.list',      description: 'List objects in a Storage bucket.',                            riskLevel: 'low'  },
      { name: 'sb.storage.get',       description: 'Get a signed URL for a Storage object.',                      riskLevel: 'low'  },
      { name: 'sb.functions.invoke',  description: 'Invoke a deployed Edge Function.',                              riskLevel: 'med'  },
    ],
    mockResources: [
      { uri: 'sb://project/{ref}',           description: 'A Supabase project.' },
      { uri: 'sb://project/{ref}/db',         description: 'The project database.' },
      { uri: 'sb://project/{ref}/auth/users', description: 'The auth user pool.' },
    ],
  },
  {
    id: 'vercel',
    label: 'Vercel',
    blurb: 'Deployments, projects, env vars, KV, Edge Config. Hobby (free) tier covers most agent use cases. Bearer-token auth.',
    icon: 'plug',
    transport: 'streamable-http',
    endpoint: 'https://api.vercel.com/mcp',
    authKinds: ['bearer', 'oauth'],
    defaultAuth: 'bearer',
    scopes: [],
    mockTools: [
      { name: 'vercel.deployments.list', description: 'List recent deployments for a project.',          riskLevel: 'low'  },
      { name: 'vercel.deployment.get',   description: 'Fetch a deployment with build logs.',              riskLevel: 'low'  },
      { name: 'vercel.deployment.cancel',description: 'Cancel an in-flight deployment.',                   riskLevel: 'med'  },
      { name: 'vercel.deployment.promote',description:'Promote a preview deployment to production.',      riskLevel: 'high' },
      { name: 'vercel.env.list',         description: 'List environment variables for a project.',         riskLevel: 'low'  },
      { name: 'vercel.env.set',          description: 'Set or update an environment variable.',            riskLevel: 'high' },
      { name: 'vercel.kv.get',           description: 'Read a key from Vercel KV.',                         riskLevel: 'low'  },
      { name: 'vercel.kv.set',           description: 'Write a key into Vercel KV.',                        riskLevel: 'med'  },
    ],
    mockResources: [
      { uri: 'vercel://project/{id}',    description: 'A Vercel project.' },
      { uri: 'vercel://deployment/{id}', description: 'A deployment with logs.' },
    ],
  },
  {
    id: 'sentry',
    label: 'Sentry',
    blurb: 'Errors, issues, releases.',
    icon: 'plug',
    transport: 'streamable-http',
    endpoint: 'https://mcp.sentry.dev',
    authKinds: ['oauth', 'bearer'],
    defaultAuth: 'oauth',
    scopes: ['project:read', 'event:read', 'issue:write'],
    mockTools: [
      { name: 'issue.list',    description: 'List unresolved issues in a project.', riskLevel: 'low' },
      { name: 'issue.resolve', description: 'Resolve an issue.',                      riskLevel: 'med' },
      { name: 'release.track', description: 'Attach a commit range to a release.',    riskLevel: 'low' },
    ],
  },
];

export const AUTH_KINDS = [
  { id: 'oauth',  label: 'OAuth 2.1',     blurb: 'User-delegated — per-user tokens via redirect flow.', recommended: true },
  { id: 'bearer', label: 'Bearer token',  blurb: 'Static service token stored in the vault.' },
  { id: 'header', label: 'Custom header', blurb: 'Arbitrary header + secret (e.g. X-API-Key).' },
  { id: 'mtls',   label: 'Mutual TLS',    blurb: 'Client certificate + private key from the vault.' },
  { id: 'none',   label: 'No auth',       blurb: 'Public endpoint. Internal networks only.' },
];

export const TRANSPORTS = [
  { id: 'streamable-http', label: 'Streamable HTTP', blurb: 'Single endpoint; server streams deltas. Most modern servers.' },
  { id: 'sse',             label: 'HTTP + SSE',      blurb: 'Older spec. /sse stream + POST tool calls.' },
  { id: 'stdio',           label: 'stdio (local)',   blurb: 'Launch a local process. Not for remote servers.' },
];

export const APPROVAL_POLICIES = [
  { id: 'per-tool', label: 'Per-tool',  desc: 'Each tool carries its own approval flag. Recommended.' },
  { id: 'always',   label: 'Always',    desc: 'Every call routes through human review.' },
  { id: 'never',    label: 'Never',     desc: 'Fully automated. High-risk tools still respect their own flag.' },
];

export const ACL_MODES = [
  { id: 'inherit',    label: 'Inherit',    desc: 'Respect the auth provider\'s own user/group scoping.' },
  { id: 'allow-list', label: 'Allow list', desc: 'Only listed SCIM groups can attach or call tools from this server.' },
];

export const vendorById = (id) => VENDORS.find(v => v.id === id) || VENDORS[0];
