/* Seed data for Context Engine — sources + corpora.
   Built with realistic enterprise shapes so the demo lands credibly:
   spend / churn / retention warehouse rows, KB documents, Salesforce
   pipeline. Numbers are deterministic per id. */

const NOW = Date.now();
const m = (n) => n * 60_000;
const h = (n) => n * 60 * 60_000;
const d = (n) => n * 24 * 60 * 60_000;

export function buildSourcesSeed() {
  return [
    {
      id: 'src_sf_analytics',
      kind: 'snowflake',
      name: 'Snowflake · Analytics',
      description: 'Source of truth for billing, vendor, and product analytics.',
      auth: { account: 'ag12345.us-east-1', role: 'AGENT_READ_RO', warehouse: 'COMPUTE_WH', credential: 'vault://snowflake/agentvault-prod' },
      props: { database: 'ANALYTICS', schema: 'PUBLIC' },
      acl_strategy: 'row',
      acl_detail: 'Snowflake role AGENT_READ_RO + row access policy by tenant_id',
      freshness_target_min: 15,
      freshness_lag_min: 4,
      sync_mode: 'scheduled',
      last_sync_at: NOW - m(4),
      row_count: 14_812_000,
      tables: 142,
      health: 'green',
      created_at: NOW - d(180),
      created_by: 'platform@latentbridge.com',
      tags: ['core', 'finance'],
    },
    {
      id: 'src_bq_telemetry',
      kind: 'bigquery',
      name: 'BigQuery · Product telemetry',
      description: 'Event stream from app + web. Partitioned daily.',
      auth: { project: 'agentvault-prod', serviceAcct: 'vault://gcp/agent-bq-ro' },
      props: { dataset: 'telemetry', location: 'US' },
      acl_strategy: 'row',
      acl_detail: 'IAM allowlist · column-level mask on `user_email`',
      freshness_target_min: 30,
      freshness_lag_min: 12,
      sync_mode: 'cdc',
      last_sync_at: NOW - m(12),
      row_count: 412_000_000,
      tables: 38,
      health: 'green',
      created_at: NOW - d(132),
      created_by: 'data-platform@latentbridge.com',
      tags: ['core', 'product'],
    },
    {
      id: 'src_db_unity',
      kind: 'databricks',
      name: 'Databricks · Customer 360',
      description: 'Unified customer table built on Unity Catalog.',
      auth: { workspaceUrl: 'https://acme.cloud.databricks.com', token: 'vault://databricks/pat-prod' },
      props: { catalog: 'main', schema: 'customer' },
      acl_strategy: 'tag',
      acl_detail: 'Unity tags `pii.high` and `pii.low` mapped to retrieval scopes',
      freshness_target_min: 10,
      freshness_lag_min: 3,
      sync_mode: 'cdc',
      last_sync_at: NOW - m(3),
      row_count: 6_240_000,
      tables: 21,
      health: 'green',
      created_at: NOW - d(91),
      created_by: 'data-eng@latentbridge.com',
      tags: ['core', 'gdpr'],
    },
    {
      id: 'src_pg_app',
      kind: 'postgres',
      name: 'Postgres · App primary',
      description: 'OLTP read replica for invoices, vendors, agents.',
      auth: { host: 'db-replica-1.acme.internal', port: 5432, credential: 'vault://postgres/app-replica-ro' },
      props: { database: 'app', replication: 'agentvault_slot' },
      acl_strategy: 'row',
      acl_detail: 'RLS on `tenants.id` propagated through pgRowLevelSecurity',
      freshness_target_min: 1,
      freshness_lag_min: 0,
      sync_mode: 'cdc',
      last_sync_at: NOW - m(0),
      row_count: 8_120_000,
      tables: 56,
      health: 'green',
      created_at: NOW - d(220),
      created_by: 'platform@latentbridge.com',
      tags: ['oltp'],
    },
    {
      id: 'src_sf_crm',
      kind: 'salesforce',
      name: 'Salesforce · CRM',
      description: 'Account, Opportunity, Case + custom Vendor object.',
      auth: { instance: 'https://latentbridge.my.salesforce.com', credential: 'vault://salesforce/oauth-rt' },
      props: { objects: 'Account, Opportunity, Case, Vendor__c' },
      acl_strategy: 'row',
      acl_detail: 'Salesforce profile-aware row-level + FLS column mask',
      freshness_target_min: 5,
      freshness_lag_min: 18,
      sync_mode: 'cdc',
      last_sync_at: NOW - m(18),
      row_count: 482_000,
      tables: 4,
      health: 'yellow',
      created_at: NOW - d(64),
      created_by: 'revops@latentbridge.com',
      tags: ['saas', 'crm'],
    },
    {
      id: 'src_sn_tickets',
      kind: 'servicenow',
      name: 'ServiceNow · Incidents + KB',
      description: 'Live incidents and the official KB articles.',
      auth: { instance: 'latentbridge.service-now.com', credential: 'vault://servicenow/api-token' },
      props: { tables: 'incident, kb_knowledge' },
      acl_strategy: 'tag',
      acl_detail: 'KB ACLs by `kb_category` + incident assignment groups',
      freshness_target_min: 10,
      freshness_lag_min: 6,
      sync_mode: 'scheduled',
      last_sync_at: NOW - m(6),
      row_count: 142_000,
      tables: 2,
      health: 'green',
      created_at: NOW - d(48),
      created_by: 'itops@latentbridge.com',
      tags: ['saas', 'support'],
    },
    {
      id: 'src_sp_ops',
      kind: 'sharepoint',
      name: 'SharePoint · Ops handbook',
      description: 'Internal handbook + runbooks. Page-permission-aware.',
      auth: { tenantId: 'a1b2c3d4-…', credential: 'vault://m365/agentvault-app' },
      props: { siteUrl: 'https://latentbridge.sharepoint.com/sites/ops', libraries: 'Documents, Runbooks' },
      acl_strategy: 'row',
      acl_detail: 'M365 site permission group → user identity claim',
      freshness_target_min: 15,
      freshness_lag_min: 9,
      sync_mode: 'scheduled',
      last_sync_at: NOW - m(9),
      row_count: 1_840,
      tables: null,
      health: 'green',
      created_at: NOW - d(31),
      created_by: 'ops@latentbridge.com',
      tags: ['docs'],
    },
    {
      id: 'src_s3_invoices',
      kind: 's3-objects',
      name: 'S3 · Invoice archives',
      description: '7-year invoice archive in Parquet, partitioned by year/month.',
      auth: { role: 'arn:aws:iam::123:role/InvoiceArchiveRO', credential: 'vault://aws/agent-s3' },
      props: { bucket: 'agentvault-invoices', prefix: 'archive/', format: 'parquet' },
      acl_strategy: 'tag',
      acl_detail: 'S3 object tag `data.classification = restricted` requires elevated scope',
      freshness_target_min: 1440,
      freshness_lag_min: 720,
      sync_mode: 'scheduled',
      last_sync_at: NOW - h(12),
      row_count: 18_400_000,
      tables: null,
      health: 'red',
      health_detail: 'Missed last scheduled sync at 02:00 UTC — credentials rotation pending',
      created_at: NOW - d(420),
      created_by: 'finance@latentbridge.com',
      tags: ['archive'],
    },
  ];
}

export function buildCorporaSeed() {
  return [
    {
      id: 'cor_finance_kpi',
      name: 'Finance KPI corpus',
      description: 'Curated tables for revenue, AP/AR, and vendor metrics. Used by Finance Analyst agents.',
      source_ids: ['src_sf_analytics', 'src_pg_app'],
      projection: {
        'src_sf_analytics': 'fct_invoices, dim_vendors, fct_revenue_daily',
        'src_pg_app':       'invoices, vendors',
      },
      chunking: { strategy: 'structured', size: 1, overlap: 0 },
      embedding: { model: 'text-embedding-3-large', dim: 3072 },
      reranker: 'cohere-rr',
      acl_inheritance: 'row',
      chunk_count: 2_412_800,
      last_reindex_at: NOW - h(6),
      drift_score: 0.04,
      ndcg_at_10: 0.94,
      recall_at_10: 0.91,
      mrr: 0.88,
      health: 'green',
      query_count_7d: 18_412,
      cost_7d_usd: 41.20,
      tags: ['finance', 'production'],
      created_at: NOW - d(64),
      created_by: 'platform@latentbridge.com',
    },
    {
      id: 'cor_customer_360',
      name: 'Customer 360 corpus',
      description: 'Unified customer view across CRM + product telemetry. PII-tagged with Unity catalog.',
      source_ids: ['src_db_unity', 'src_sf_crm'],
      projection: {
        'src_db_unity': 'customer.fct_customer_master, customer.fct_health_score',
        'src_sf_crm':   'Account, Opportunity',
      },
      chunking: { strategy: 'parent-child', size: 800, overlap: 100 },
      embedding: { model: 'voyage-3', dim: 1024 },
      reranker: 'voyage-rr',
      acl_inheritance: 'tag',
      chunk_count: 614_300,
      last_reindex_at: NOW - h(2),
      drift_score: 0.02,
      ndcg_at_10: 0.91,
      recall_at_10: 0.88,
      mrr: 0.85,
      health: 'green',
      query_count_7d: 9_842,
      cost_7d_usd: 28.40,
      tags: ['customer', 'production'],
      created_at: NOW - d(48),
      created_by: 'data-eng@latentbridge.com',
    },
    {
      id: 'cor_support_kb',
      name: 'Support knowledge base',
      description: 'KB articles + active incidents. Tagged by ServiceNow KB category.',
      source_ids: ['src_sn_tickets', 'src_sp_ops'],
      projection: {
        'src_sn_tickets': 'kb_knowledge, incident (last 90d)',
        'src_sp_ops':     'Documents/runbooks/*',
      },
      chunking: { strategy: 'semantic', size: 1200, overlap: 0 },
      embedding: { model: 'text-embedding-3-small', dim: 1536 },
      reranker: 'cohere-rr',
      acl_inheritance: 'tag',
      chunk_count: 84_120,
      last_reindex_at: NOW - h(1),
      drift_score: 0.03,
      ndcg_at_10: 0.89,
      recall_at_10: 0.84,
      mrr: 0.82,
      health: 'yellow',
      health_detail: 'Drift up 1.4% week-over-week — schedule reindex',
      query_count_7d: 24_120,
      cost_7d_usd: 18.60,
      tags: ['support', 'production'],
      created_at: NOW - d(28),
      created_by: 'itops@latentbridge.com',
    },
    {
      id: 'cor_vendor_risk',
      name: 'Vendor risk + sanctions',
      description: 'Vendor records joined with sanctions watchlist embeddings.',
      source_ids: ['src_pg_app', 'src_sf_crm'],
      projection: {
        'src_pg_app': 'vendors, vendor_documents',
        'src_sf_crm': 'Vendor__c',
      },
      chunking: { strategy: 'fixed', size: 800, overlap: 100 },
      embedding: { model: 'cohere-embed-v3', dim: 1024 },
      reranker: 'none',
      acl_inheritance: 'row',
      chunk_count: 240_400,
      last_reindex_at: NOW - h(18),
      drift_score: 0.07,
      ndcg_at_10: 0.86,
      recall_at_10: 0.79,
      mrr: 0.78,
      health: 'yellow',
      query_count_7d: 1_840,
      cost_7d_usd: 12.10,
      tags: ['risk', 'kyc'],
      created_at: NOW - d(40),
      created_by: 'compliance@latentbridge.com',
    },
    {
      id: 'cor_invoice_archive',
      name: 'Invoice archive (7y)',
      description: 'Long-tail invoice corpus. Slow refresh, restricted-class data.',
      source_ids: ['src_s3_invoices'],
      projection: {
        'src_s3_invoices': 'archive/year=*/month=*',
      },
      chunking: { strategy: 'structured', size: 1, overlap: 0 },
      embedding: { model: 'text-embedding-3-small', dim: 1536 },
      reranker: 'none',
      acl_inheritance: 'tag',
      chunk_count: 18_400_000,
      last_reindex_at: NOW - d(1),
      drift_score: 0.01,
      ndcg_at_10: 0.81,
      recall_at_10: 0.74,
      mrr: 0.71,
      health: 'red',
      health_detail: 'Source S3 archive failed last sync — corpus may be stale',
      query_count_7d: 240,
      cost_7d_usd: 4.80,
      tags: ['archive'],
      created_at: NOW - d(120),
      created_by: 'finance@latentbridge.com',
    },
  ];
}
